// FETCH USERS
export const FETCH_CARERS_REQUEST = 'FETCH_CARERS_REQUEST'
export const FETCH_CARERS_SUCCESS = 'FETCH_CARERS_SUCCESS'
export const FETCH_CARERS_FAILURE = 'FETCH_CARERS_FAILURE'

// SESSION
export const GET_CURRENT_USER = 'GET_CURRENT_USER'
export const LOGOUT_CURRENT_USER = 'LOGOUT_CURRENT_USER'

export const RECEIVE_SESSION_ERRORS = 'RECEIVE_SESSION_ERRORS'


