export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'

export const CREATE_USER = 'CREATE_USER';
export const FORM_SUBMISSION_STATUS = 'FORM_SUBMISSION_STATUS' 