export const FETCH_CARERS_REQUEST = 'FETCH_CARERS_REQUEST'
export const FETCH_CARERS_SUCCESS = 'FETCH_CARERS_SUCCESS'
export const FETCH_CARERS_FAILURE = 'FETCH_CARERS_FAILURE'

export const CREATE_USER = 'CREATE_USER';
export const FORM_SUBMISSION_STATUS = 'FORM_SUBMISSION_STATUS' 