export const FETCH_CARERS_REQUEST = 'FETCH_CARERS_REQUEST'
export const FETCH_CARERS_SUCCESS = 'FETCH_CARERS_SUCCESS'
export const FETCH_CARERS_FAILURE = 'FETCH_CARERS_FAILURE'

export const GET_CURRENT_USER = 'GET_CURRENT_USER'
export const LOGOUT_CURRENT_USER = 'LOGOUT_CURRENT_USER'

export const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM'
export const RESET_LOGIN_FORM = 'RESET_LOGIN_FORM'
